name: Generate feed
on:
  schedule:
  - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write  # 游녣 p콏id치 opr치vn캩n칤 k z치pisu do repozit치콏e

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install requests

      - name: Generate filtered feed
        run: python filter_feed.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed_instock.xml
          git commit -m "Update feed" || echo "No changes"
          git push
