name: Generate feed
on:
  schedule:
    - cron: "0 3 * * *"  # každý den ve 3:00 ráno
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Generate filtered feed
        run: python filter_feed.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed_instock.xml
          git commit -m "Update feed" || echo "No changes"
          git push
